### ISSUE TITLE
有写书源模版吗

### ISSUE THREAD

**Issue by Haishengl** [zhishuapp/zhishuapp.github.io#10]
写源模版吗，佬。发一个给我呗，我也想写几个有

**Comment by Haishengl** [comment]
有写源模版吗大佬

**Comment by sososdk** [comment]
@Haishengl 书源使用的是 https://github.com/open-source-scripts 库


安装书源开发工具: 
- [工具使用文档](https://github.com/open-source-scripts/open-source-scripts-VSCode-Extension?tab=readme-ov-file#%E4%BD%BF%E7%94%A8-usage)(文档未完善, 有些信息可能有误)
- [下载插件](https://github.com/open-source-scripts/open-source-scripts-VSCode-Extension/releases/tag/v1.0.6)
- 从 vscode 扩展的右上角选择 Install from VSIX 安装上面的插件
- 新建项目 (New Project) [ CTRL+ALT+6 N ]
- 参考 `source/example.com.js` 写脚本, 也可以参考[书源相关文档](https://github.com/open-source-scripts)
- 参考其他脚本 https://github.com/open-source-scripts/book-scripts-third-party
- 建立设备连接
    - 在知书->我的->开启开发者服务
    - 建立设备连接 (Connect) [ Ctrl+Alt+F6 ]
- 调试: 打开要调试的脚本, 运行脚本 (Run) [ F6 ]
