### ISSUE TITLE
主要是手机写源

### ISSUE THREAD

**Issue by Haishengl** [zhishuapp/zhishuapp.github.io#11]
刚才没说清楚，大佬。是在手机上写源的模版，身边没电脑操作

**Comment by Haishengl** [comment]
刚才没说清楚，大佬。是手机上写源的模版，身边没电脑操作

**Comment by sososdk** [comment]
手机上写起来太不方便了. 你看不到其他网站的数据, 没办法写啊

**Comment by Haishengl** [comment]
我有抓包软件呀大佬，有个模版的话就好写了

**Comment by sososdk** [comment]
@Haishengl 这个模版: https://github.com/open-source-scripts/open-source-scripts-VSCode-Extension/blob/master/assets/template/sources/example.com.js

参考其他脚本 https://github.com/open-source-scripts/book-scripts-third-party

**Comment by Haishengl** [comment]
好的，谢谢大佬
