### ISSUE TITLE
关于升级与阅读源兼容的建议

### ISSUE THREAD

**Issue by chineselzh** [zhishuapp/zhishuapp.github.io#12]
建议如下：
1.建议我的--设置页里增加检测更新相关选项。
2.建议兼容阅读APP的阅读源。
谢谢！感谢大大！

**Comment by sososdk** [comment]
> 1.建议我的--设置页里增加检测更新相关选项。

收到

> 2.建议兼容阅读APP的阅读源。

这个搞不了, 阅读书源规则太复杂了

**Comment by chineselzh** [comment]
@sososdk 大大，这个应用非常好，可以上架到酷安APP（应该需要备案）和奇妙应用APP（应该不需要备案），让大家都接触到这个相当nice的APP。

**Comment by sososdk** [comment]
未来会上架应用市场, 现在APP功能还不够完善.
