### ISSUE TITLE
epub格式

### ISSUE THREAD

**Issue by Fan-Bob** [zhishuapp/zhishuapp.github.io#16]
不支持epub格式的书籍，书架导入

**Comment by sososdk** [comment]
@Fan-Bob 方便上传书籍文件吗？

**Comment by Fan-Bob** [comment]
当然可以
https://drive.google.com/file/d/1oH8SYmZABkCCJfPmmkl_0eoAXQs45yPn/view?usp=drivesdk
一本来自菠萝包的轻小说epub
（使用moon+Reader可以打开）

**Comment by Fan-Bob** [comment]
顺便提个小小的建议，阅读中两边的留白有点过于多了，影响第一观感

**Comment by sososdk** [comment]
@Fan-Bob 边距在阅读页面的设置里面可以调整 ![961716169119_ pic](https://github.com/zhishuapp/zhishuapp.github.io/assets/46806014/c4b346cb-73a3-4a75-885e-8858a58d5b50)

**Comment by Fan-Bob** [comment]
好的，能修复一下不支持导入部分本地阅读的bug吗，这本txt也是，其它本地阅读器能打开，知书无法打开
https://drive.google.com/file/d/1pA0-ucdmIN7TmTZQ7mvfW6FiJvWvAL6y/view?usp=drivesdk

**Comment by sososdk** [comment]
已修复, 跟随下个版本更新.
