### ISSUE TITLE
bug，边距

### ISSUE THREAD

**Issue by Fan-Bob** [zhishuapp/zhishuapp.github.io#17]
![Screenshot_20240521-013901](https://github.com/zhishuapp/zhishuapp.github.io/assets/139612414/ae709057-aa36-41b6-8c7d-574a4686714d)
![Screenshot_20240521-013950](https://github.com/zhishuapp/zhishuapp.github.io/assets/139612414/2e0bf02c-5bcc-47b3-aad4-98e514a70c0d)
左右间距都为0的情况下，右侧留白依旧很明显

**Comment by sososdk** [comment]
有些奇怪~ 从没遇到这种情况. @Fan-Bob 能提供一下你的手机型号和系统吗?

我的手机看到是这样的:
![981716247107_ pic_hd](https://github.com/zhishuapp/zhishuapp.github.io/assets/46806014/17ab38b6-d2ad-4e02-a59a-d5f30080c9d9)

**Comment by Fan-Bob** [comment]
我的系统是Pixel OS（Aosp系统），安卓版本是A14
![Screenshot_20240523-105508](https://github.com/zhishuapp/zhishuapp.github.io/assets/139612414/4289b7c9-687d-4860-8d2d-2d5d546e4ac7)

**Comment by sososdk** [comment]
已修复, 跟随下个版本更新.
