### ISSUE TITLE
请求增加阅读app书源链接的导入

### ISSUE THREAD

**Issue by bingsunny0730** [zhishuapp/zhishuapp.github.io#19]
目前自带的开源书源不是很多，而且发现部分书源失效或出现乱码的情况，大佬能否兼容下开源阅读书源的导入？毕竟同样是json脚本链接，而且阅读书源仓库的更新维护比较多，要是支持的话就更加完美了
![sshot-2024-05-25- 13-16-18](https://github.com/zhishuapp/zhishuapp.github.io/assets/131505889/9f918c7e-1bef-4bd0-b779-f4eb5f8f4e37)

**Comment by sososdk** [comment]
阅读的书源格式太复杂了, 兼容不了
