### ISSUE TITLE
epub本地书籍无法加载

### ISSUE THREAD

**Issue by bingsunny0730** [zhishuapp/zhishuapp.github.io#20]
部分epub兼容性不是很好，尤其是图片、章节内容无法加载，而使用其它阅读器却没问题。另外，希望支持拖拽导入的功能吧。
![sshot-2024-05-25- 13-30-03](https://github.com/zhishuapp/zhishuapp.github.io/assets/131505889/fe3e0448-e8d8-4a16-bc08-cf4766c89840)
![sshot-2024-05-25- 13-29-27](https://github.com/zhishuapp/zhishuapp.github.io/assets/131505889/d7d6a3f8-a27b-4ba6-abdb-c6b5d6f3fcc0)

**Comment by sososdk** [comment]
@bingsunny0730 可以将epub文件上传一下吗?

**Comment by bingsunny0730** [comment]
文件在此：https://f.ws59.cn/f/e71xda4xtrp

**Comment by sososdk** [comment]
已修复, 跟随下个版本更新.
