### ISSUE TITLE
建议书源js头部增加强制白名单机制

### ISSUE THREAD

**Issue by zeromake** [zhishuapp/zhishuapp.github.io#27]
js 的方式制作书源简单，但是在书源里投毒也很简单，希望支持第三方额外书源导入时必须确认可以访问的 host，防止有的兄弟制作书源被投毒后到处投放（当然导入时如果不注意也是没办法的），示例 `@whitelist xxx` 
```js
// ==UserScript==
// @name          xxx
// @domain        m.douyinxs.com
// @description   xxx
// @version       0.0.1
// @icon          xx
// @supportURL    https://github.com/open-source-scripts/book-scripts/issues
// @function      search
// @function      toc
// @function      chapter
// @whitelist      https://m.douyinxs.com
// ==/UserScript==
```

**Comment by zeromake** [comment]
顺便一提，没有电脑端模拟器，做一个书源要累死了，经常js报错，但是没有第几行……

**Comment by sososdk** [comment]
@zeromake 访问白名单的功能已经有定义, 但是没有开放. 因为目前看来好像没有这个必要, 脚本只能调用应用提供的功能, 无法对用户造成影响. 如果确实有必要, 以后再开放.

关于写书源:

如果是电脑的话, 建议使用 `知书` 配合 `vscode` 可以很方便编写和测试书源.  
vscode 插件: [open-source-scripts-VSCode-Extension](https://github.com/open-source-scripts/open-source-scripts-VSCode-Extension/releases/tag/v1.0.6)        
请查看插件使用[文档](https://github.com/open-source-scripts/open-source-scripts-VSCode-Extension?tab=readme-ov-file#%E4%BD%BF%E7%94%A8-usage)(文档未完善, 有些信息可能有误)

如果是手机的话, 编辑书源建议使用第三方编辑器, 编写好之后再复制到应用内进行调试. 应用内报错, `长按报错图标可以显示错误信息`.

<img width="310" alt="image" src="https://github.com/user-attachments/assets/ff6c3861-759c-4cfb-9f43-d57fbdf823f1">
