### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by rosiapng** [zhishuapp/zhishuapp.github.io#3]
你好，把你的App分享给网友，他们都很喜欢你的搜书排版. 
有位朋友问能不能有自定义背景图片的功能呢？
能不能有净化功能吗？还有翻阅能不能加多一个无效果吗？

还有这个AP P会不会上架？我们IOS使用者都很期待你这款软件

**Comment by sososdk** [comment]
> 能不能有自定义背景图片的功能呢？

暂时应该不会有自定义背景功能
> 能不能有净化功能吗？

阅读页面, 右上角有净化功能
> 翻阅能不能加多一个无效果吗？

功能是有的, 只是不好排版, 所以没开放
> 这个AP P会不会上架？

暂时不会上架. iOS 目前只能自签名使用

**Comment by endbosszgsm1** [comment]
！[上传IMG_3292.png...]()
番茄无法打开看小说，

**Comment by sososdk** [comment]
暂时没办法
