### ISSUE TITLE
webdav链接阿里云盘，使用aliyundrive-webdav接口提示Invalid http date

### ISSUE THREAD

**Issue by jexxagn** [zhishuapp/zhishuapp.github.io#7]
使用备份恢复功能，webdav链接阿里云盘，使用aliyundrive-webdav接口提示Invalid http date...，麻烦处理

**Comment by jexxagn** [comment]
ios16.6

**Comment by sososdk** [comment]
把配置截图我看看

**Comment by sososdk** [comment]
我用 alist 和 坚果 的webdav都是没问题的，你也可以试一下

**Comment by jexxagn** [comment]
![IMG_1130](https://github.com/zhishuapp/zhishuapp.github.io/assets/34477160/6cfd9542-1f51-48ca-9c01-dcd29dc716ba)

我用alist也是有问题，一样的错误，alist挂载的阿里云盘，是不是和阿里云盘有关系

**Comment by jexxagn** [comment]
坚果没有问题，alist 百度网盘也没问题，确认了就是alist阿里云盘有问题

**Comment by sososdk** [comment]
@jexxagn 我的alist阿里云盘没问题，你试试修改一下子文件夹
![Screenshot_20240425_061953_com.github.sososdk.zhishu.dev_edit_392164538934951.jpg](https://github.com/zhishuapp/zhishuapp.github.io/assets/46806014/24a6683a-f30c-485e-8887-291d628e8959)

**Comment by sososdk** [comment]
已修复, 将在下版本更新
